server:
  port: 9003

spring:
  http:
    encoding:     #解决读取配置乱码显示问题
      force: true
      charset: UTF-8
      enabled: true
  application:
    name: cloudalibaba-sentinel-ribbon-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848    #nacos注册中心地址
    sentinel:
      transport:
        #配置Sentinel dashboard 地址
        dashboard: localhost:8080
        #默认8191端口，假如被占用会自动从8719开始一次 +1 扫描，直至找到未被占用的端口
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*' #被监控的内容需要暴露端口