server:
  port: 8001

spring:
  application:
    name: cloud-prover-hystrix-service

eureka:
  client:
    register-with-eureka: true  #true表示把自己注册进eurekaServer，默认为true
    fetch-registry: true   #true表示从eurekaServer抓取已有的注册信息，默认为true.单节点无所谓，集群必须设置为true才能配合rebbon使用负载均衡
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka/