server:
  port: 3344

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

#rabbitmq相关配置
rabbitmq:
  host: localhost   #rabbitmq地址
  port: 5672  #rabbitmq端口
  username: guest
  password: guest

#暴露bus刷新配置的端点
management:
  endpoints:  #暴露bug刷新配置的端点
  web:
    exposure:
      include: 'bus-refresh'


spring:
 http:
  encoding:     #解决读取配置乱码显示问题
    force: true
    charset: UTF-8
    enabled: true
  application:
   name: cloud-config-center
 cloud:
   config:
     server:
       git:
         uri: https://github.com/xuliang-config/FirstTest.git  #github上面的git仓库名字
         username: xuliang-config     #git登录账户密码
         password: xuliang136543
         #搜索目录，如果文件是直接放在仓库下，可以不写搜索配置，默认从仓库下找
         #如果存在多级目录，可以在这里配置，这样页面请求配置文件时可以少写目录路径
         search-paths:
           - FirstTest
         force-pull: true
     label: master    #默认分支，不写也默认为master