server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  devtools:
    restart:
      poll-interval: 3000ms
      quiet-period: 2999ms
  cloud:
    zookeeper:
      connect-string: 39.97.190.43:2181