server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.97.190.43:3306/springcloud?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://39.97.190.43:3306/springcloud?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
    username: root
    password: xuliang136543
  devtools:
    restart:
      poll-interval: 3000ms
      quiet-period: 2999ms

mybatis:
  mapper-locations: classpath:mapper/*.xml  #指定mapper文件的位置
  #指定POJO扫描包来让mybatis自动扫描到自定义POJO，用于resultMap和parameterType
  type-aliases-package: com.atguigu.springcloud.entities



eureka:
  instance:
    instance-id: payment8001  #主机名
    prefer-ip-address: true  #访问路径可以显示IP地址
  client:
    register-with-eureka: true  #true表示把自己注册进eurekaServer，默认为true
    fetch-registry: true   #true表示从eurekaServer抓取已有的注册信息，默认为true.单节点无所谓，集群必须设置为true才能配合rebbon使用负载均衡
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka/