server:
  port: 9527

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment-routh1                #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001        #匹配后提供服务的路由地址
          uri: lb://cloud-prover-hystrix-service       #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/hystrix/ok/**   #断言，路径相匹配的进行路由
#            - After=2021-03-09T10:38:48.779+08:00[Asia/Shanghai]
#            - Before=2021-03-09T10:38:48.779+08:00[Asia/Shanghai]
#            - Between=2021-03-09T10:38:48.779+08:00[Asia/Shanghai],2021-03-09T11:38:48.779+08:00[Asia/Shanghai]

        - id: payment-routh2
          uri: lb://cloud-prover-hystrix-service
          predicates:
            - Path=/payment/hystrix/no/**
#            - Cookie=username,xl
            - Method=GET  #要求为get请求
#            - Query=username,\d+

#        - id: payment-routh3
#          uri: http://news.baidu.com/guonei
#          predicates:
#            - Path=/guonei/**
  application:
    name: cloud-gateway

eureka:
  client:
    register-with-eureka: true  #true表示把自己注册进eurekaServer，默认为true
    fetch-registry: true   #true表示从eurekaServer抓取已有的注册信息，默认为true.单节点无所谓，集群必须设置为true才能配合rebbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址