
spring:
  application:
    name: seata-A
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848    #nacos注册中心地址
    alibaba:
      seata:
        tx-service-group: fps_tx_group  #自定义事务组名称需要与seata-server中的对应
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.97.190.43:3306/seata_a?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false
    #    url: jdbc:mysql://39.97.190.43:3306/springcloud?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
    username: root
    password: xuliang136543

mybatis:
  mapper-locations: classpath:mapper/*.xml  #指定mapper文件的位置

logging:
  level:
    io:
      seata: info
server:
  port: 2000